# Reference:
# 1. https://github.com/actions/starter-workflows/blob/main/deployments/azure-webapps-node.yml
name: Deploy for staging version

on:
  push:
    branches:
      - dev/duonghuy # Deploy when code is pushed to 'develop'

env:
  WEBAPP_NAME: data-lake # set this to your application's name
  WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "20.x" # set this to the node version to use

# permissions:
#   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Working Directory
        run: pwd

      - name: Create an .env file in frontend for building image
        run: |
          echo "VITE_API=${{ secrets.VITE_API }}" > ./fe-modul-report/.env

      - name: List Files
        run: ls -laR

      - name: Run Makefiles with Secrets to build anh push docker images to dockerhub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          make staging
          ls -al .env
          cat .env
          cp .env deployment/staging/
          cp .env deployment/staging/deploy.env

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_DUONGHUY_HOST }}
          username: ${{ secrets.STAGING_DUONGHUY_USER }}
          key: ${{ secrets.STAGING_DUONGHUY_SSH_KEY }}
          port: ${{ secrets.STAGING_DUONGHUY_PORT }}
          script: |
            mkdir -p /home/${{ secrets.STAGING_DUONGHUY_USER }}/data-lake/duonghuy/deployment/staging

      - name: Transfer docker-compose file to VPS for deployment
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGING_DUONGHUY_HOST }}
          username: ${{ secrets.STAGING_DUONGHUY_USER }}
          key: ${{ secrets.STAGING_DUONGHUY_SSH_KEY }}
          port: ${{ secrets.STAGING_DUONGHUY_PORT }}
          source: "deployment/staging/*,deployment/staging/.env"
          target: "/home/${{ secrets.STAGING_DUONGHUY_USER }}/data-lake/duonghuy/deployment/staging"
          strip_components: 2 # Removes "deployment/staging/" folder path!

      - name: Clean up containers and stuff via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_DUONGHUY_HOST }}
          username: ${{ secrets.STAGING_DUONGHUY_USER }}
          key: ${{ secrets.STAGING_DUONGHUY_SSH_KEY }}
          port: ${{ secrets.STAGING_DUONGHUY_PORT }}
          script: |
            # Change to staging deployment directory
            cd /home/${{ secrets.STAGING_DUONGHUY_USER }}/data-lake/duonghuy/deployment/staging 
            if [ -f deploy.env ]; then cp -f deploy.env .env; fi
            # Debug info
            pwd
            ls -al
            cat .env
            docker image prune -f
            docker compose -f staging-docker-compose.yaml down # always down first
            docker ps

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_DUONGHUY_HOST }}
          username: ${{ secrets.STAGING_DUONGHUY_USER }}
          key: ${{ secrets.STAGING_DUONGHUY_SSH_KEY }}
          port: ${{ secrets.STAGING_DUONGHUY_PORT }}
          script: |
            ### Change to staging deployment directory
            cd /home/${{ secrets.STAGING_DUONGHUY_USER }}/data-lake/duonghuy/deployment/staging 
            if [ -f deploy.env ]; then cp -f deploy.env .env; fi
            sed -i 's/\r$//' start-app.sh || true
            chmod +x start-app.sh
            ./start-app.sh
